# Generated by Django 3.2 on 2021-04-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=50)),
                ('vendor_surname', models.CharField(blank=True, max_length=100)),
                ('vendor_dni', models.CharField(blank=True, max_length=9)),
                ('vendor_address', models.CharField(blank=True, max_length=150)),
                ('vendor_province', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
