# Generated by Django 3.2.2 on 2021-05-13 15:56

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_auto_20210513_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='path',
            field=models.FilePathField(blank=True, null=True, path=pathlib.PurePosixPath('/home/jsv/Documents/CARRERA/tfg4/rasa-chatbot/api/media')),
        ),
    ]
