# Generated by Django 3.2.2 on 2021-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0004_contrato_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
